name: Validate CSV presence

on:
  pull_request:
    branches: [ "**" ]

jobs:
  validate-csv:
    name: Check shirlei_report_all_data.csv exists and is valid
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure CSV file exists at repo root
        run: |
          if [ ! -f "shirlei_report_all_data.csv" ]; then
            echo "ERROR: shirlei_report_all_data.csv not found at repo root." >&2
            exit 1
          fi

      - name: Ensure CSV is non-empty
        run: |
          if [ ! -s "shirlei_report_all_data.csv" ]; then
            echo "ERROR: shirlei_report_all_data.csv is empty." >&2
            exit 1
          fi

      - name: Validate header contains required columns
        run: |
          header=$(head -n 1 shirlei_report_all_data.csv)
          echo "CSV header: $header"
          req_cols=("date_received" "RequestType")
          missing=0
          for col in "${req_cols[@]}"; do
            if ! echo "$header" | grep -q "$col"; then
              echo "ERROR: Required column '$col' not found in header." >&2
              missing=1
            fi
          done
          if [ "$missing" -ne 0 ]; then
            exit 1
          fi

      - name: Basic CSV format sanity (at least 2 rows total)
        run: |
          line_count=$(wc -l < shirlei_report_all_data.csv)
          echo "Line count: $line_count"
          if [ "$line_count" -lt 2 ]; then
            echo "ERROR: CSV should contain a header and at least one data row." >&2
            exit 1
          fi

      - name: Success
        run: echo "CSV validation passed."
